import type { Reservacion } from "../domain/reservacion";

export const MOCK_RESERVACIONES: readonly Reservacion[] = Object.freeze([
  {
    id: "1",
    codigo: "RES-001",
    huesped: { nombre: "María García", email: "maria.garcia@email.com", iniciales: "MG" },
    habitacion: { nombre: "Suite Panorámica", ubicacion: "Piso 12 · Vista al mar" },
    checkIn: "2026-04-20",
    checkOut: "2026-04-25",
    noches: 5,
    totalUSD: 1250,
    estado: "pendiente",
  },
  {
    id: "2",
    codigo: "RES-002",
    huesped: { nombre: "Carlos Rodríguez", email: "carlos.r@email.com", iniciales: "CR" },
    habitacion: { nombre: "Habitación Deluxe", ubicacion: "Piso 8 · Vista al jardín" },
    checkIn: "2026-04-18",
    checkOut: "2026-04-21",
    noches: 3,
    totalUSD: 540,
    estado: "aprobada",
  },
  {
    id: "3",
    codigo: "RES-003",
    huesped: { nombre: "Ana Martínez", email: "ana.m@email.com", iniciales: "AM" },
    habitacion: { nombre: "Habitación Estándar", ubicacion: "Piso 4 · Vista interior" },
    checkIn: "2026-04-10",
    checkOut: "2026-04-12",
    noches: 2,
    totalUSD: 220,
    estado: "completada",
  },
  {
    id: "4",
    codigo: "RES-004",
    huesped: { nombre: "Luis Fernández", email: "lfernandez@email.com", iniciales: "LF" },
    habitacion: { nombre: "Suite Ejecutiva", ubicacion: "Piso 15 · Vista a la ciudad" },
    checkIn: "2026-04-22",
    checkOut: "2026-04-28",
    noches: 6,
    totalUSD: 1800,
    estado: "aprobada",
  },
  {
    id: "5",
    codigo: "RES-005",
    huesped: { nombre: "Sofia Vargas", email: "sofia.v@email.com", iniciales: "SV" },
    habitacion: { nombre: "Habitación Deluxe", ubicacion: "Piso 6 · Vista al mar" },
    checkIn: "2026-04-15",
    checkOut: "2026-04-17",
    noches: 2,
    totalUSD: 360,
    estado: "cancelada",
  },
  {
    id: "6",
    codigo: "RES-006",
    huesped: { nombre: "Diego Mora", email: "diego.mora@email.com", iniciales: "DM" },
    habitacion: { nombre: "Habitación Estándar", ubicacion: "Piso 3 · Vista interior" },
    checkIn: "2026-05-01",
    checkOut: "2026-05-04",
    noches: 3,
    totalUSD: 330,
    estado: "pendiente",
  },
]);
