export const HERO = Object.freeze({
  SECTION: "relative min-h-screen flex flex-col overflow-hidden bg-forest-950",
  BG_LAYER: "absolute inset-0 pointer-events-none",
  CONTAINER: "relative z-10 flex flex-col flex-1 max-w-[1440px] mx-auto w-full px-6 lg:px-16",
  CONTENT_WRAPPER: "flex flex-col lg:flex-row items-center flex-1 gap-16 pt-36 pb-24 lg:pt-44 lg:pb-32",
  LEFT: "flex flex-col gap-8 lg:w-[55%]",
  RIGHT: "lg:w-[45%] flex items-center justify-center lg:justify-end w-full",
  EYEBROW: "text-xs tracking-[0.35em] uppercase text-gold-400 font-sans",
  WORDMARK: "font-serif text-[3.5rem] lg:text-[4.5rem] font-normal tracking-[0.25em] text-stone-50 leading-none",
  HEADLINE: "font-serif text-[4rem] lg:text-[6rem] xl:text-[7rem] leading-[0.95] text-stone-50 font-normal",
  SUBHEADLINE: "text-stone-300 text-base lg:text-lg leading-relaxed max-w-md font-light",
  CTA_ROW: "flex flex-wrap gap-4 pt-2",
  CTA_PRIMARY: "inline-flex items-center gap-2 px-8 py-4 bg-gold-500 text-forest-950 text-sm font-medium tracking-widest uppercase transition-all duration-500 hover:bg-gold-400 hover:scale-[1.02]",
  CTA_SECONDARY: "inline-flex items-center gap-2 px-8 py-4 border border-stone-600 text-stone-300 text-sm font-medium tracking-widest uppercase transition-all duration-500 hover:border-gold-500 hover:text-gold-400",
  LOCATION_BAR: "flex items-center gap-4 pt-4",
  LOCATION_LINE: "flex-1 h-px bg-stone-800",
  LOCATION_TEXT: "text-xs tracking-[0.25em] uppercase text-stone-500 whitespace-nowrap",
  SCROLL_CUE: "absolute bottom-10 left-1/2 -translate-x-1/2 flex flex-col items-center gap-3 z-10",
  SCROLL_TEXT: "text-xs tracking-[0.3em] uppercase text-stone-500",
  SCROLL_LINE: "w-px h-12 bg-gradient-to-b from-stone-500 to-transparent",
  VISUAL_PANEL: "relative w-full max-w-[480px] aspect-[3/4] rounded-sm overflow-hidden",
  VISUAL_INNER: "absolute inset-0",
  VISUAL_BADGE: "absolute bottom-6 left-6 right-6 p-4 backdrop-blur-sm bg-forest-950/70 border border-stone-700/40",
  VISUAL_BADGE_TEXT: "text-xs tracking-[0.25em] uppercase text-stone-400",
  VISUAL_BADGE_TITLE: "text-sm font-serif text-stone-100 mt-1",
} as const);
