export const LABEL_KEYS = Object.freeze({
  DASHBOARD: "DASHBOARD",
  ADMINS: "ADMINS",
  RESERVATIONS: "RESERVATIONS",
  CLIENTS: "CLIENTS",
  ROOMS: "ROOMS",
  INVOICES: "INVOICES",
  CMS_LANDING: "CMS_LANDING",
});
