export const UPDATE_PERMISSION_ERRORS = {
  SELF_MODIFY: "SELF_MODIFY",
  OWNER_MODIFY: "OWNER_MODIFY",
  INVALID_PERMISSION: "INVALID_PERMISSION",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type UpdatePermissionError =
  (typeof UPDATE_PERMISSION_ERRORS)[keyof typeof UPDATE_PERMISSION_ERRORS];
