export const GALLERY = Object.freeze({
  SECTION: "relative bg-forest-950 py-24 lg:py-36",
  CONTAINER: "max-w-[1440px] mx-auto px-6 lg:px-16",
  HEADER: "text-center max-w-2xl mx-auto mb-16 lg:mb-24 flex flex-col items-center gap-4",
  HEADLINE_WRAPPER: "overflow-hidden",
  EYEBROW: "text-xs tracking-[0.35em] uppercase text-gold-400 font-sans",
  HEADLINE: "font-serif text-[2.5rem] lg:text-[4rem] leading-[1.05] text-stone-50 font-normal",
  SUBHEADLINE: "text-stone-400 text-base lg:text-lg leading-relaxed font-light",
  STAGE: "relative h-[420px] lg:h-[480px] w-full",
  STAGE_INNER: "absolute inset-0 flex items-center justify-center",
  CARD_OVERLAY: "absolute inset-0",
  CAROUSEL_WRAPPER: "hidden lg:block",
  CARD: "absolute rounded-2xl overflow-hidden select-none",
  CARD_CLICKABLE: "cursor-pointer",
  CARD_INNER: "w-full h-full relative",
  CARD_OVERLAY_PATTERN: "absolute inset-0 opacity-[0.035]",
  CARD_GRADIENT_BOTTOM: "absolute inset-x-0 bottom-0 h-[45%]",
  CARD_TEXT_AREA: "absolute inset-x-0 bottom-0 p-7 flex flex-col",
  CARD_ACCENT_LINE: "w-6 h-px bg-gold-500/60 mb-4",
  CARD_DOT: "absolute top-5 right-5 w-1.5 h-1.5 rounded-full bg-gold-500/50",
  CARD_TITLE: "font-serif text-stone-50 text-xl leading-tight",
  CARD_SUBTITLE: "font-sans text-stone-300/70 text-[11px] tracking-[0.2em] uppercase mt-1.5",
  CONTROLS: "mt-10 flex items-center justify-center gap-2.5",
  CONTROLS_WRAPPER: "flex flex-col items-center gap-4 mt-6",
  PROGRESS_BG: "w-20 h-px bg-forest-700 overflow-hidden rounded-full",
  PROGRESS_FILL: "h-full bg-gold-500/40 origin-left",
  DOT_ACTIVE: "w-5 h-[3px] rounded-full bg-gold-500 transition-all duration-400",
  DOT_INACTIVE: "w-[3px] h-[3px] rounded-full bg-forest-600 hover:bg-forest-500 transition-all duration-300",
  MOBILE_WRAPPER: "lg:hidden flex gap-4 overflow-x-auto snap-x snap-mandatory pb-4 -mx-6 px-6 scrollbar-none mt-2",
  MOBILE_CARD: "snap-start shrink-0 w-[74vw] rounded-xl overflow-hidden",
  MOBILE_CARD_INNER: "w-full h-full relative",
  MOBILE_GRADIENT: "absolute inset-x-0 bottom-0 h-2/5",
  MOBILE_TEXT_AREA: "absolute inset-x-0 bottom-0 p-5 flex flex-col",
  MOBILE_ACCENT_LINE: "w-5 h-px bg-gold-500/60 mb-3",
  MOBILE_CARD_TITLE: "font-serif text-stone-50 text-lg leading-tight",
  MOBILE_CARD_SUBTITLE: "font-sans text-stone-300/70 text-[10px] tracking-[0.2em] uppercase mt-1",
  MOBILE_CARD_DOT: "absolute top-4 right-4 w-1.5 h-1.5 rounded-full bg-gold-500",
} as const);
