import type { Reservation } from "../domain/reservation";

export const MOCK_RESERVATIONS: readonly Reservation[] = Object.freeze([
  {
    id: "6",
    code: "RES-006",
    guest: { name: "Diego Mora", email: "diego.mora@email.com", initials: "DM" },
    room: { name: "Habitación Estándar", location: "Piso 3 · Vista interior" },
    checkIn: "2026-05-01",
    checkOut: "2026-05-04",
    nights: 3,
    totalUSD: 330,
    status: "pending",
  },
  {
    id: "4",
    code: "RES-004",
    guest: { name: "Luis Fernández", email: "lfernandez@email.com", initials: "LF" },
    room: { name: "Suite Ejecutiva", location: "Piso 15 · Vista a la ciudad" },
    checkIn: "2026-04-22",
    checkOut: "2026-04-28",
    nights: 6,
    totalUSD: 1800,
    status: "approved",
  },
  {
    id: "1",
    code: "RES-001",
    guest: { name: "María García", email: "maria.garcia@email.com", initials: "MG" },
    room: { name: "Suite Panorámica", location: "Piso 12 · Vista al mar" },
    checkIn: "2026-04-20",
    checkOut: "2026-04-25",
    nights: 5,
    totalUSD: 1250,
    status: "pending",
  },
  {
    id: "2",
    code: "RES-002",
    guest: { name: "Carlos Rodríguez", email: "carlos.r@email.com", initials: "CR" },
    room: { name: "Habitación Deluxe", location: "Piso 8 · Vista al jardín" },
    checkIn: "2026-04-18",
    checkOut: "2026-04-21",
    nights: 3,
    totalUSD: 540,
    status: "approved",
  },
  {
    id: "5",
    code: "RES-005",
    guest: { name: "Sofia Vargas", email: "sofia.v@email.com", initials: "SV" },
    room: { name: "Habitación Deluxe", location: "Piso 6 · Vista al mar" },
    checkIn: "2026-04-15",
    checkOut: "2026-04-17",
    nights: 2,
    totalUSD: 360,
    status: "cancelled",
  },
  {
    id: "3",
    code: "RES-003",
    guest: { name: "Ana Martínez", email: "ana.m@email.com", initials: "AM" },
    room: { name: "Habitación Estándar", location: "Piso 4 · Vista interior" },
    checkIn: "2026-04-10",
    checkOut: "2026-04-12",
    nights: 2,
    totalUSD: 220,
    status: "completed",
  },
  {
    id: "7",
    code: "RES-007",
    guest: { name: "Valeria Cruz", email: "valeria.cruz@email.com", initials: "VC" },
    room: { name: "Suite Junior", location: "Piso 10 · Vista al jardín" },
    checkIn: "2026-05-03",
    checkOut: "2026-05-07",
    nights: 4,
    totalUSD: 760,
    status: "pending",
  },
  {
    id: "8",
    code: "RES-008",
    guest: { name: "Andrés Salazar", email: "andres.salazar@email.com", initials: "AS" },
    room: { name: "Suite Presidencial", location: "Piso 18 · Vista panorámica" },
    checkIn: "2026-04-30",
    checkOut: "2026-05-05",
    nights: 5,
    totalUSD: 2500,
    status: "approved",
  },
  {
    id: "9",
    code: "RES-009",
    guest: { name: "Camila Porras", email: "camila.porras@email.com", initials: "CP" },
    room: { name: "Habitación Familiar", location: "Piso 5 · Vista al jardín" },
    checkIn: "2026-04-26",
    checkOut: "2026-04-29",
    nights: 3,
    totalUSD: 690,
    status: "completed",
  },
  {
    id: "10",
    code: "RES-010",
    guest: { name: "Jorge Herrera", email: "jorge.herrera@email.com", initials: "JH" },
    room: { name: "Habitación Estándar", location: "Piso 2 · Vista interior" },
    checkIn: "2026-05-08",
    checkOut: "2026-05-10",
    nights: 2,
    totalUSD: 240,
    status: "cancelled",
  },
]);