export const DASHBOARD_HEADER_STYLES = {
  wrapper:       "flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between",
  left:          "space-y-1",
  titleRow:      "flex items-baseline gap-2 flex-wrap",
  titlePrefix:   "text-3xl font-bold text-gray-900 tracking-tight",
  titleAccent:   "text-3xl font-bold text-emerald-600 tracking-tight italic",
  subtitle:      "text-sm text-gray-500",
  controls:      "flex items-center gap-2 shrink-0",
  dateGroup:     "flex items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-3 py-2 shadow-sm",
  calendarIcon:  "size-4 text-gray-400 shrink-0",
  segment:       "text-sm text-gray-700 focus:outline-none",
  separator:     "text-gray-400 text-sm mx-1",
  triggerIndicator: "text-gray-400 hover:text-gray-600",
  yearPickerTrigger: "flex items-center gap-1 text-sm font-medium",
  yearPickerTriggerHeading: "font-semibold",
  yearPickerTriggerIndicator: "size-4",
  navButton:     "flex size-8 items-center justify-center rounded-lg hover:bg-gray-100",
  calendarCell:  "flex size-8 items-center justify-center rounded-lg text-sm hover:bg-emerald-50 data-[selected]:bg-emerald-500 data-[selected]:text-white data-[in-range]:bg-emerald-100",
  yearPickerCell: "flex h-9 items-center justify-center rounded-lg text-sm hover:bg-gray-100 data-[selected]:bg-emerald-500 data-[selected]:text-white",
  exportButton:  "flex items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 transition-colors",
  exportIcon:    "size-4 text-gray-500",
} as const;
