export const ABOUT = Object.freeze({
  SECTION: "relative overflow-hidden bg-stone-50",
  CONTAINER: "max-w-[1440px] mx-auto px-6 lg:px-16 py-32 lg:py-44",
  GRID: "grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24 items-start",
  TEXT_PANEL: "flex flex-col",
  EYEBROW: "text-xs tracking-[0.35em] uppercase text-gold-600 font-sans mb-6",
  HEADLINE_WRAPPER: "overflow-hidden mb-8",
  HEADLINE:
    "font-serif text-[2.5rem] lg:text-[3.5rem] leading-[1.1] text-forest-900 font-normal text-balance mb-8",
  HEADLINE_NO_MB:
    "font-serif text-[2.5rem] lg:text-[3.5rem] leading-[1.1] text-forest-900 font-normal text-balance",
  BODY: "text-stone-600 text-base lg:text-lg leading-relaxed font-light mb-8",
  QUOTE_WRAPPER: "border-l-2 border-gold-500 pl-6",
  QUOTE: "font-serif text-xl lg:text-2xl italic text-forest-800 leading-relaxed",
  QUOTE_ATTR: "text-xs tracking-[0.25em] uppercase text-stone-400 mt-3",
  MOSAIC: "grid grid-cols-2 gap-3",
  MOSAIC_TALL: "col-span-1 row-span-2",
  MOSAIC_ITEM: "rounded-sm overflow-hidden",
  MOSAIC_INNER: "w-full h-full relative",
  OVERLAY: "absolute inset-0",
  STATS: "grid grid-cols-2 lg:grid-cols-4 border-t border-stone-200 mt-20 lg:mt-32",
  STAT_ITEM: "py-10 px-8 border-r border-b lg:border-b-0 border-stone-200 last:border-r-0",
  STAT_VALUE: "font-serif text-[3rem] lg:text-[3.5rem] leading-none text-forest-900",
  STAT_LABEL: "text-xs tracking-[0.25em] uppercase text-stone-400 mt-2",
} as const);
