export const SIDEBAR_STYLES = {
  wrapper: "flex h-screen flex-col border-r border-gray-200 bg-white",
  expanded: "w-72",
  collapsed: "w-20",
  header: "flex items-center justify-between border-b border-gray-100 px-4 py-4",
  logo: "flex items-center gap-3 text-sm font-semibold uppercase tracking-[0.2em] text-gray-700",
  collapseButton: "h-9 w-9 text-gray-600",
  body: "flex-1 overflow-y-auto px-3 py-4",
  section: "mb-6",
  sectionTitle: "px-2 pb-2 text-xs font-semibold uppercase tracking-[0.18em] text-gray-400",
  navItem:
    "flex items-center gap-3 rounded-xl px-3 py-2 text-sm font-medium text-gray-600 transition-colors",
  navItemActive: "bg-gray-900 text-white shadow-sm",
  navItemInactive: "hover:bg-gray-100",
  icon: "h-5 w-5",
  footer: "border-t border-gray-100 px-4 py-4",
  identity: "flex items-center gap-3",
  identityText: "min-w-0 flex-1",
  identityName: "truncate text-sm font-semibold text-gray-900",
  identityRole: "truncate text-xs uppercase tracking-[0.18em] text-gray-500",
  logoutButton: "mt-3 w-full justify-start text-gray-600",
  collapsedLabel: "sr-only",
} as const;
