export const RESERVATION_STATUS_ACTIONS = {
  SELECT_STATUS: "SELECT_STATUS",
  UPDATE_CANCELLATION_REASON: "UPDATE_CANCELLATION_REASON",
  REVERT_CHANGES: "REVERT_CHANGES",
  SAVE_COMMITTED: "SAVE_COMMITTED",
} as const;
