import { THEME_COLORS, THEME_INTERACTIONS } from "../../../constants/info.constants";

export const ROOM_INFO_FORM_STYLES = {
  container: `w-full max-w-4xl mx-auto bg-white rounded-[32px] overflow-hidden shadow-[0_40px_100px_-20px_rgba(0,0,0,0.1)] border border-${THEME_COLORS.BORDER}`,
  header: `p-10 pb-6 bg-gradient-to-br from-[${THEME_COLORS.SUBTLE}] to-white border-b border-[${THEME_COLORS.BORDER}]`,
  title: `text-4xl font-black tracking-tight text-[${THEME_COLORS.ACCENT}] font-instrument-sans`,
  subtitle: `text-[13px] font-medium text-[${THEME_COLORS.LABEL}] uppercase tracking-widest mt-2`,
  form: "p-10 flex flex-col gap-10",
  grid: "grid grid-cols-1 md:grid-cols-2 gap-8",
  fullWidth: "w-full",
  section: "flex flex-col gap-6",
  sectionTitle: `text-[12px] font-black uppercase tracking-[0.2em] text-[${THEME_COLORS.PRIMARY}] mb-4 flex items-center gap-3 before:content-[''] before:w-6 before:h-[2px] before:bg-[${THEME_COLORS.PRIMARY}]`,
  fieldGroup: "flex flex-col gap-2.5",
  label: `text-[11px] font-black uppercase tracking-[0.1em] text-[${THEME_COLORS.LABEL}] ml-1`,
  input: `rounded-2xl border-[${THEME_COLORS.BORDER}] focus:border-[${THEME_COLORS.PRIMARY}] transition-all duration-200 w-full`,
  inputWrapper: "relative flex items-center w-full",
  inputIcon: `absolute left-5 z-10 text-[${THEME_COLORS.LABEL}] pointer-events-none`,
  inputWithIcon: "pl-12",
  selectTrigger: `rounded-2xl border-[${THEME_COLORS.BORDER}] focus:border-[${THEME_COLORS.PRIMARY}] h-14 bg-white`,
  listBox: `rounded-2xl border-[${THEME_COLORS.BORDER}] shadow-xl p-2`,
  actions: `flex justify-end items-center gap-6 mt-4 pt-10 border-t border-[${THEME_COLORS.BORDER}]`,
  submitButton: `bg-[${THEME_COLORS.PRIMARY}] text-white font-black uppercase tracking-widest text-[13px] px-10 py-5 rounded-2xl transition-all duration-${THEME_INTERACTIONS.TRANSITION_DURATION} hover:opacity-90 hover:shadow-[0_20px_40px_-10px_rgba(0,0,0,0.2)] active:scale-[${THEME_INTERACTIONS.ACTIVE_SCALE}]`,
  cancelButton: `bg-transparent text-[${THEME_COLORS.LABEL}] font-black uppercase tracking-widest text-[13px] px-8 py-4 rounded-2xl transition-all duration-${THEME_INTERACTIONS.TRANSITION_DURATION} hover:text-gray-900 active:scale-[${THEME_INTERACTIONS.ACTIVE_SCALE}]`,
  switchContainer: `flex items-center justify-between p-6 bg-[${THEME_COLORS.SUBTLE}] rounded-[24px] border border-[${THEME_COLORS.BORDER}] transition-all hover:border-[${THEME_COLORS.PRIMARY}]`,
  switchLabel: `text-[13px] font-bold text-[${THEME_COLORS.ACCENT}]`,
} as const;
