import { THEME_COLORS, THEME_INTERACTIONS } from "../../../constants/info.constants";

export const ROOM_INFO_FORM_STYLES = {
  container: "w-full max-w-5xl mx-auto",
  headerWrapper: "mb-16 text-center",
  title: `text-6xl font-black tracking-tighter text-[${THEME_COLORS.ACCENT}] font-instrument-sans leading-tight`,
  subtitle: `text-[14px] font-bold text-[${THEME_COLORS.PRIMARY}] uppercase tracking-[0.3em] mt-6 block`,
  form: "flex flex-col gap-20",
  section: "relative",
  sectionHeader: "flex flex-col gap-2 mb-8",
  sectionTitle: `text-[13px] font-black uppercase tracking-[0.25em] text-[${THEME_COLORS.LABEL}] flex items-center gap-4 before:content-[''] before:w-10 before:h-[2px] before:bg-[${THEME_COLORS.PRIMARY}]`,
  card: `bg-white/80 backdrop-blur-2xl rounded-[48px] p-12 border border-white shadow-[0_40px_100px_-20px_rgba(0,128,100,0.08)] transition-all hover:shadow-[0_50px_120px_-20px_rgba(0,128,100,0.12)]`,
  grid: "grid grid-cols-1 md:grid-cols-2 gap-10",
  fullWidth: "w-full",
  fieldGroup: "flex flex-col gap-3",
  label: `text-[12px] font-black uppercase tracking-widest text-[${THEME_COLORS.LABEL}] ml-2`,
  input: `rounded-[24px] border-[${THEME_COLORS.BORDER}] focus:border-[${THEME_COLORS.PRIMARY}] h-14 px-6 bg-white/50 transition-all focus:bg-white focus:ring-4 focus:ring-[${THEME_COLORS.PRIMARY}]/10`,
  selectTrigger: `rounded-[24px] border-[${THEME_COLORS.BORDER}] focus:border-[${THEME_COLORS.PRIMARY}] h-16 bg-white/50 px-6`,
  listBox: `rounded-[32px] border-[${THEME_COLORS.BORDER}] shadow-2xl p-4 bg-white/90 backdrop-blur-xl`,
  actions: "flex justify-center items-center gap-8 mt-12",
  submitButton: `bg-[${THEME_COLORS.PRIMARY}] text-white font-black uppercase tracking-[0.2em] text-[14px] px-14 py-6 rounded-full transition-all duration-500 hover:scale-105 hover:shadow-[0_20px_50px_-10px_rgba(0,128,100,0.3)] active:scale-95`,
  cancelButton: `bg-white text-[${THEME_COLORS.LABEL}] font-black uppercase tracking-[0.2em] text-[12px] px-10 py-5 rounded-full border border-[${THEME_COLORS.BORDER}] transition-all hover:bg-gray-50 active:scale-95`,
  switchCard: `group flex items-center justify-between p-8 bg-white rounded-[32px] border border-[${THEME_COLORS.BORDER}] transition-all hover:border-[${THEME_COLORS.PRIMARY}] hover:shadow-xl hover:-translate-y-1`,
  switchLabel: `text-[15px] font-black text-[${THEME_COLORS.ACCENT}] tracking-tight`,
  inputWrapper: "relative flex items-center w-full",
  inputIcon: `absolute left-6 z-10 text-[${THEME_COLORS.PRIMARY}] pointer-events-none`,
  inputWithIcon: "pl-14",
} as const;
