import { THEME_COLORS, THEME_INTERACTIONS } from "../../../constants/info.constants";

export const ROOM_INFO_FORM_STYLES = {
  container: "w-full max-w-5xl mx-auto",
  headerWrapper: "mb-16 text-center drop-shadow-2xl",
  title: "text-6xl font-black tracking-tighter text-white font-instrument-sans leading-tight",
  subtitle: "hidden",
  form: "flex flex-col gap-8",
  section: "relative",
  sectionHeader: "flex flex-col items-center gap-1 mb-6",
  sectionTitle: `text-[11px] font-black uppercase tracking-[0.3em] text-[${THEME_COLORS.LABEL}] text-center`,
  card: `bg-white/80 backdrop-blur-xl rounded-[32px] p-6 border border-white shadow-[0_20px_60px_-15px_rgba(0,128,100,0.06)] transition-all hover:shadow-[0_30px_80px_-15px_rgba(0,128,100,0.1)]`,
  grid: "grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6",
  fullWidth: "w-full",
  fieldGroup: "flex flex-col gap-3",
  label: `text-[12px] font-black uppercase tracking-widest text-[${THEME_COLORS.LABEL}] ml-2`,
  input: `rounded-[24px] border-[${THEME_COLORS.BORDER}] focus:border-[${THEME_COLORS.PRIMARY}] h-14 px-6 bg-white/50 transition-all focus:bg-white focus:ring-4 focus:ring-[${THEME_COLORS.PRIMARY}]/10`,
  selectTrigger: `rounded-[24px] border-[${THEME_COLORS.BORDER}] focus:border-[${THEME_COLORS.PRIMARY}] h-16 bg-white/50 px-6`,
  listBox: `rounded-[32px] border-[${THEME_COLORS.BORDER}] shadow-2xl p-4 bg-white/90 backdrop-blur-xl`,
  actions: "flex justify-center items-center gap-6 mt-8",
  submitButton: `bg-emerald-600 text-white font-black uppercase tracking-[0.15em] text-[13px] px-12 py-5 rounded-full transition-all duration-300 hover:scale-105 hover:bg-emerald-500 hover:shadow-[0_15px_40px_-10px_rgba(16,185,129,0.4)] active:scale-95`,
  cancelButton: `bg-white text-rose-600 font-black uppercase tracking-[0.15em] text-[13px] px-12 py-5 rounded-full border-2 border-rose-100 transition-all hover:bg-rose-50 hover:border-rose-200 active:scale-95`,
  switchCard: `group flex items-center justify-between p-6 bg-white rounded-[24px] border border-[${THEME_COLORS.BORDER}] transition-all hover:border-[${THEME_COLORS.PRIMARY}] hover:shadow-lg`,
  switchLabel: `text-[15px] font-black text-[${THEME_COLORS.ACCENT}] tracking-tight`,
  inputWrapper: "relative flex items-center w-full",
  inputIcon: `absolute left-6 z-10 text-[${THEME_COLORS.PRIMARY}] pointer-events-none`,
  inputWithIcon: "pl-14",
  hint: `text-[10px] text-[${THEME_COLORS.LABEL}]/60 leading-relaxed text-center mt-auto pt-6 px-4 italic`,
} as const;
